[[VegaFusion]]
arch = "aarch64"
git-tree-sha1 = "552442f9b17f5b438bd14f66ce650c9d557b6d2d"
os = "macos"

    [[VegaFusion.download]]
    sha256 = "d1bee94ebeb2c700571d588545a7b41172315c0b48f31b482c56c300d35bb490"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.2.0+0/VegaFusion.v0.2.0.aarch64-apple-darwin.tar.gz"
[[VegaFusion]]
arch = "aarch64"
git-tree-sha1 = "3cbcab6fdcf6ba4084a4c5d923f81ede0f24686f"
libc = "glibc"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "76c1c28b18ef4052901400bafdbbd9f1ddca4c68a491d4cb7af4c96a7b7d0858"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.2.0+0/VegaFusion.v0.2.0.aarch64-linux-gnu.tar.gz"
[[VegaFusion]]
arch = "aarch64"
git-tree-sha1 = "e30ffd917f7739e4267373b299a434bae1f33ab6"
libc = "musl"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "651c69099b3a97d3fddb7764d6c306884eac2134d48ad7d75c3b0fe099d27042"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.2.0+0/VegaFusion.v0.2.0.aarch64-linux-musl.tar.gz"
[[VegaFusion]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e6284055135a731d0d1eecf7da0ae0f19c24590a"
libc = "glibc"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "e5e688ae2730d26f09ff5fb7a369ef65e08602cc26a123d71b08e69eae7a39cf"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.2.0+0/VegaFusion.v0.2.0.armv6l-linux-gnueabihf.tar.gz"
[[VegaFusion]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d78a2076a6320d745f18e88db8dd026801400042"
libc = "musl"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "25dd21b786edbad9bfd9e70d60ed70b4ca8cdab56b1bb3076b1fd6b09ea98508"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.2.0+0/VegaFusion.v0.2.0.armv6l-linux-musleabihf.tar.gz"
[[VegaFusion]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f500a7c8bac61ff5dbedf5bdb33c8c9248577fc6"
libc = "glibc"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "ab5c948d2066e23032cda058340863cc21e00b4460e255b0ce8145809ee94797"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.2.0+0/VegaFusion.v0.2.0.armv7l-linux-gnueabihf.tar.gz"
[[VegaFusion]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7d5c629b0a201e6fd61dd948a4715b95240f5da6"
libc = "musl"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "94fa4f746e108b6237c865b85a171a83487ec08cb81bb0a497dd7e099e04a9fb"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.2.0+0/VegaFusion.v0.2.0.armv7l-linux-musleabihf.tar.gz"
[[VegaFusion]]
arch = "x86_64"
git-tree-sha1 = "55e546a3b9aff62459e7ed0730a0e8f839a7c0b6"
os = "macos"

    [[VegaFusion.download]]
    sha256 = "0fc95f04f55f3c8e055d044d23a9905df7fc56f7de29693734c4c781b21612e1"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.2.0+0/VegaFusion.v0.2.0.x86_64-apple-darwin.tar.gz"
[[VegaFusion]]
arch = "x86_64"
git-tree-sha1 = "26d13e8379bba11e1bf69db6286c4883f38b121d"
libc = "glibc"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "4080c56e5109939398fed3614ea0ba7170c3b825550969357aa8bc168546a8ef"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.2.0+0/VegaFusion.v0.2.0.x86_64-linux-gnu.tar.gz"
[[VegaFusion]]
arch = "x86_64"
git-tree-sha1 = "c29bef324e6b3f167f02eeacf04d87baf6c89e5e"
libc = "musl"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "ab5eff926d4f9b848d818992f71555efaa50acd4c1e7033c98dcf29e328f551e"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.2.0+0/VegaFusion.v0.2.0.x86_64-linux-musl.tar.gz"
[[VegaFusion]]
arch = "x86_64"
git-tree-sha1 = "b44387e64450e0a63838f9496664af0bc4858b33"
os = "freebsd"

    [[VegaFusion.download]]
    sha256 = "0a383daa85bcc9a6eb539d04bb2cf762a3e14beec6342093b52ff2921462cebb"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.2.0+0/VegaFusion.v0.2.0.x86_64-unknown-freebsd.tar.gz"
[[VegaFusion]]
arch = "x86_64"
git-tree-sha1 = "2e1fbf7a7ca4b07f8230809b0488f4d2e2636330"
os = "windows"

    [[VegaFusion.download]]
    sha256 = "2a98b0d0e0f26c88adb4b83b867d5c975ca24c09bd44d458d236893267b07b4b"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.2.0+0/VegaFusion.v0.2.0.x86_64-w64-mingw32.tar.gz"
