[[VegaFusion]]
arch = "aarch64"
git-tree-sha1 = "1737c089689713265675bb65b3144954a6031e15"
os = "macos"

    [[VegaFusion.download]]
    sha256 = "70aa15b62d80b5cf9e75e082c310e7b668c927517543e584feff70820ea0e7a6"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.10.0+0/VegaFusion.v0.10.0.aarch64-apple-darwin.tar.gz"
[[VegaFusion]]
arch = "aarch64"
git-tree-sha1 = "1fd6e838f3d7ae88f685ae0b715965dbb350c0d6"
libc = "glibc"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "c36dd7f2a4000c6d94ee78114153e2ebf3101e862fc0addf52a5430705c0c948"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.10.0+0/VegaFusion.v0.10.0.aarch64-linux-gnu.tar.gz"
[[VegaFusion]]
arch = "aarch64"
git-tree-sha1 = "7310c0f2a8b6b6565f2935639235c45141f8724e"
libc = "musl"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "ea3fbfd687d48d15bfc1ec791c83f11c77e373af5ed8e9102df79060a1fdc97d"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.10.0+0/VegaFusion.v0.10.0.aarch64-linux-musl.tar.gz"
[[VegaFusion]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2446c8035845455f4383b2e69f42c6b0aa433e5a"
libc = "glibc"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "259afab55f67d6cf21a46b26f8d6fc86441fe064026cb06629f195f351404f3d"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.10.0+0/VegaFusion.v0.10.0.armv6l-linux-gnueabihf.tar.gz"
[[VegaFusion]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c96a14212045a28d81e6aa0b7cf5f2a759893488"
libc = "musl"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "df618e5145c4a972f2adb48ad4d6df387bfdcc0c99d97b3223503171647d26b8"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.10.0+0/VegaFusion.v0.10.0.armv6l-linux-musleabihf.tar.gz"
[[VegaFusion]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "53af8e19d91143d458e0fae4b11ca875bb058275"
libc = "glibc"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "b77fc6c32f27a8b6843ef46979407303419222b9c78ddad0a18f4e428d65aed3"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.10.0+0/VegaFusion.v0.10.0.armv7l-linux-gnueabihf.tar.gz"
[[VegaFusion]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c87a42f71e95d23d1ac872da8ca7626038a73c12"
libc = "musl"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "493a37ae04283f88adc9c4fcff68a76312875e7387e63a8e13c36027f67b8abb"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.10.0+0/VegaFusion.v0.10.0.armv7l-linux-musleabihf.tar.gz"
[[VegaFusion]]
arch = "x86_64"
git-tree-sha1 = "04477ff9d59264cd15141e0c95f5891bfe296123"
os = "macos"

    [[VegaFusion.download]]
    sha256 = "63befe4c5aaeb5b9da38c5c09c0d38a6044e6a70e98f64415617d35a9abfe331"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.10.0+0/VegaFusion.v0.10.0.x86_64-apple-darwin.tar.gz"
[[VegaFusion]]
arch = "x86_64"
git-tree-sha1 = "5d422a92cdf6b24a047712d5a153137886d6ad8b"
libc = "glibc"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "084835014cf4d978604c024143d4f083d3a430cac4a6d4b7271a21ad669cda38"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.10.0+0/VegaFusion.v0.10.0.x86_64-linux-gnu.tar.gz"
[[VegaFusion]]
arch = "x86_64"
git-tree-sha1 = "32dd54d674d725aea79c2a24e45b659494eaa97b"
libc = "musl"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "b668bf8518a228b6038a39a538aa7fe9d5f0e440a0811ab0b0d4a0f4c488eec8"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.10.0+0/VegaFusion.v0.10.0.x86_64-linux-musl.tar.gz"
[[VegaFusion]]
arch = "x86_64"
git-tree-sha1 = "5b249d6d1b31d4326ad01cdf4830c2a937cad0a3"
os = "freebsd"

    [[VegaFusion.download]]
    sha256 = "12e782f4c5e4f9dfc68329db72afed3db9226a4be4199e2f2fe12a2ebcac5462"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.10.0+0/VegaFusion.v0.10.0.x86_64-unknown-freebsd.tar.gz"
[[VegaFusion]]
arch = "x86_64"
git-tree-sha1 = "b5823daa0d8acfd060c5aa94f007bf0db953fee3"
os = "windows"

    [[VegaFusion.download]]
    sha256 = "ca6f6ace45375717cfc2cde858f5a8978f9ee3d20f882a8f5363d6aa5f9f5dc8"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.10.0+0/VegaFusion.v0.10.0.x86_64-w64-mingw32.tar.gz"
