[[VegaFusion]]
arch = "aarch64"
git-tree-sha1 = "a75ce18896a9567b3f82ce6f1022a67bdf81fd7e"
os = "macos"

    [[VegaFusion.download]]
    sha256 = "20907c31dc1a9fb077e88e26ac1ec15131e3c1f26181d14dda1d4354419156a3"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.1.0+0/VegaFusion.v0.1.0.aarch64-apple-darwin.tar.gz"
[[VegaFusion]]
arch = "aarch64"
git-tree-sha1 = "cbdfd48856be7198f4386a521798277a5164c6b3"
libc = "glibc"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "96bb774bb30eb80de6731cdc9922bcf6e80cb97e03c5c9cd4138277a6615aaa3"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.1.0+0/VegaFusion.v0.1.0.aarch64-linux-gnu.tar.gz"
[[VegaFusion]]
arch = "aarch64"
git-tree-sha1 = "5303a6e1fc256179a8d6075a52b264c10b660a81"
libc = "musl"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "0f0b51343a8654675b753e4630c69836448bd31bffbb98ae0ebc132292ef2e55"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.1.0+0/VegaFusion.v0.1.0.aarch64-linux-musl.tar.gz"
[[VegaFusion]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e3c3ba09e8fb1fc4c07da03430791db7791146a5"
libc = "glibc"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "fe19713e70b3537e58b5452ce678861f4939ca0312a04fee296ee7857bf7125a"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.1.0+0/VegaFusion.v0.1.0.armv6l-linux-gnueabihf.tar.gz"
[[VegaFusion]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "57cf0291ea429c14676ba8e9ad438394fb78edf6"
libc = "musl"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "f7c97830d433cfc64e3240b476043690e1a5a644df6201b3c0709f2e3b396cf3"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.1.0+0/VegaFusion.v0.1.0.armv6l-linux-musleabihf.tar.gz"
[[VegaFusion]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b63b001a156bdd31064bf82901e98b54843c07ec"
libc = "glibc"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "d1fe1d023f7175f1f14f948b35562125871b998e4e61630619ebbb65ade46f13"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.1.0+0/VegaFusion.v0.1.0.armv7l-linux-gnueabihf.tar.gz"
[[VegaFusion]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0bb653edeec7ff1369172c2e17988f88102033cd"
libc = "musl"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "cf848dca9395d42dca209c75036260d1c313be60632d3bdb37909db752e5b952"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.1.0+0/VegaFusion.v0.1.0.armv7l-linux-musleabihf.tar.gz"
[[VegaFusion]]
arch = "x86_64"
git-tree-sha1 = "5d7a557d136dc9d7fbd2d08a8d1866fb79c1af08"
os = "macos"

    [[VegaFusion.download]]
    sha256 = "1eed808da61efd33cfd4785d9e6e96b1d9cd8eeb2ec81de903c16b4594db985a"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.1.0+0/VegaFusion.v0.1.0.x86_64-apple-darwin.tar.gz"
[[VegaFusion]]
arch = "x86_64"
git-tree-sha1 = "d2a37324932bee109262a245e12e8405f7b1fb47"
libc = "glibc"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "6f1fcbc7127f18788f4835c25d77bb4357e685e0e7a474af2935bb3e49c34805"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.1.0+0/VegaFusion.v0.1.0.x86_64-linux-gnu.tar.gz"
[[VegaFusion]]
arch = "x86_64"
git-tree-sha1 = "879ecf87e124830e1ea458ff6fbc4ff37cae7819"
libc = "musl"
os = "linux"

    [[VegaFusion.download]]
    sha256 = "d00fc1e162c4aa0bef7864e3e0c7c3382f9a517402f236cbe8c750e76cec73ad"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.1.0+0/VegaFusion.v0.1.0.x86_64-linux-musl.tar.gz"
[[VegaFusion]]
arch = "x86_64"
git-tree-sha1 = "156027bb33dfd4b4b7d0125c06cd68b151c64a11"
os = "freebsd"

    [[VegaFusion.download]]
    sha256 = "551b0e4db8f6f24aefe282f17b5cd8dca3368de42fb23618842f20c552eb9d27"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.1.0+0/VegaFusion.v0.1.0.x86_64-unknown-freebsd.tar.gz"
[[VegaFusion]]
arch = "x86_64"
git-tree-sha1 = "71811453045b851b383e1b571561b596dbabbe5c"
os = "windows"

    [[VegaFusion.download]]
    sha256 = "69bfd7a22e4e0c9a15fc51416c48f8839c732ac5a479d1e5b91b6d43f70f3455"
    url = "https://github.com/JuliaBinaryWrappers/VegaFusion_jll.jl/releases/download/VegaFusion-v0.1.0+0/VegaFusion.v0.1.0.x86_64-w64-mingw32.tar.gz"
